// Test for the generate-problems.js script.
//
// Verifies that the generator produces valid output from the real CSV
// and rejects malformed input. Run with: node scripts/generate-problems.test.js

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const SCRIPT = path.join(__dirname, 'generate-problems.js');
const CSV_PATH = path.join(ROOT, 'resources', 'problem-codes.csv');
const OUT_PATH = path.join(ROOT, 'src', 'problems.ts');

let failures = 0;

function assert(condition, message) {
  if (!condition) {
    console.error(`  FAIL: ${message}`);
    failures++;
  }
}

// --- Test 1: Generator produces valid output from real CSV ---
console.log('Test: generator produces valid output from real CSV');
execSync(`node ${SCRIPT}`, { cwd: ROOT });

const output = fs.readFileSync(OUT_PATH, 'utf-8');

// Read CSV to know what we expect
const csvText = fs.readFileSync(CSV_PATH, 'utf-8');
const csvLines = csvText.trimEnd().split('\n').slice(1).filter(l => l.trim() !== '');

for (const line of csvLines) {
  const first = line.indexOf(',');
  const second = line.indexOf(',', first + 1);
  const code = line.slice(0, first).trim();
  const name = line.slice(first + 1, second).trim();
  const message = line.slice(second + 1).trim();

  assert(output.includes(`${name}: "${code}"`), `ProblemCode should contain ${name}: "${code}"`);
  assert(output.includes(`"${message}"`), `PROBLEM_MESSAGES should contain message "${message}"`);
}

assert(output.includes('export function formatProblem'), 'Output should contain formatProblem function');
assert(output.includes('// This file is automatically generated'), 'Output should contain generated header');

// --- Test 2: Generator fails on malformed CSV ---
console.log('Test: generator fails on malformed CSV');
const tmpCsv = path.join(ROOT, 'resources', 'problem-codes.csv.bak');
const malformedCsv = 'Bad,Header\nno-commas\n';

// Backup and replace
fs.copyFileSync(CSV_PATH, tmpCsv);
try {
  fs.writeFileSync(CSV_PATH, malformedCsv, 'utf-8');
  try {
    execSync(`node ${SCRIPT}`, { cwd: ROOT, stdio: 'pipe' });
    assert(false, 'Generator should have failed on malformed CSV');
  }
  catch {
    // Expected failure
  }
}
finally {
  // Restore
  fs.copyFileSync(tmpCsv, CSV_PATH);
  fs.unlinkSync(tmpCsv);
}

// Re-generate the correct file after restoring CSV
execSync(`node ${SCRIPT}`, { cwd: ROOT });

// --- Summary ---
if (failures > 0) {
  console.error(`\n${failures} test(s) failed.`);
  process.exit(1);
}
else {
  console.log('\nAll generator tests passed.');
}
