[package]
name = "ironplc-sources"
description = "Source file handling and parsing for IronPLC"
version = "0.241.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ironplc-dsl = { path = "../dsl", version = "0.241.0" }
ironplc-parser = { path = "../parser", version = "0.241.0" }
ironplc-problems = { path = "../problems", version = "0.241.0" }

log = "0.4.29"
encoding_rs = "0.8"
roxmltree = { version = "0.21", features = ["positions"] }
time = "0.3.47"
toml = "1.1"

[build-dependencies]
ironplc-spec-requirements-gen = { path = "../spec_requirements_gen" }

[dev-dependencies]
ironplc-test = { path = "../test", version = "0.241.0" }
tempfile = "3.27"
ctor = "1.0"
env_logger = "0.11"
spec_test_macro = { path = "../spec_test_macro" }

[lints]
workspace = true
