set windows-shell := ["powershell.exe", "-c"]

alias ci := default
default: setup test

setup:
  pip install -r compatibility_resolver/requirements.txt

test:
  python -m pytest compatibility_resolver/ -v
