'''
Defines a directive that formats problem codes and automatically generates the problem index.
'''
import csv
import re
from pathlib import Path
from sphinx.locale import _
from docutils import nodes
from docutils.parsers.rst import Directive
from sys import exit
from os import listdir
from os.path import join

# Check that for each problem code that the compiler can emit that we have a file
# for that code and create a variable with the message text.
compiler_help_topics = set([v.split('.')[0] for v in listdir(join('reference', 'compiler', 'problems'))])
extension_help_topics = set([v.split('.')[0] for v in listdir(join('reference', 'editor', 'problems'))])
runtime_help_topics = set([v.split('.')[0] for v in listdir(join('reference', 'runtime', 'problems'))])
help_topics = compiler_help_topics.union(extension_help_topics).union(runtime_help_topics)
problem_infos = dict()

class ProblemCode:
    def __init__(self, message):
        self.message = message

definitions = [
    join('..', 'compiler', 'problems', 'resources', 'problem-codes.csv'),
    join('..', 'integrations', 'vscode', 'resources', 'problem-codes.csv'),
    join('..', 'compiler', 'vm', 'resources', 'problem-codes.csv'),
    join('..', 'compiler', 'vm-cli', 'resources', 'problem-codes.csv'),
]

for definition in definitions:
    with open(definition) as fp:
        problem_codes = csv.reader(fp)
        # Skip the header
        next(problem_codes)

        for row in problem_codes:
            code = row[0]
            if code not in help_topics:
                print('Missing help topic for ' + code)
                exit(1)
            problem_infos[code] = ProblemCode(row[2])

class ProblemSummary(Directive):
    required_arguments = 1
    def run(self):
        code = self.arguments[0]
        message = problem_infos[code].message

        items = [
            ProblemSummary.make_item('Code', code),
            ProblemSummary.make_item('Message', message),
        ]
        
        return [nodes.definition_list('', *items)]
    
    @staticmethod
    def make_item(key, value):
        return nodes.definition_list_item(
            '',
            nodes.term('', '', nodes.strong(text=key)),
            nodes.definition('', nodes.paragraph(text=value))
            )

def _generate_index_for(logger, srcdir, subdir, prefix_char, title):
    """Generate a problem codes index.rst for the given subdirectory and prefix."""
    problems_dir = srcdir / subdir
    index_path = problems_dir / 'index.rst'

    if not problems_dir.exists():
        logger.warning(f"Problems directory not found: {problems_dir}")
        return

    # Find all .rst files that match the pattern <prefix>####.rst
    pattern = re.compile(rf'{prefix_char}\d+\.rst$')
    problem_files = []
    for file_path in problems_dir.glob(f'{prefix_char}*.rst'):
        if pattern.match(file_path.name) and file_path.name != 'index.rst':
            problem_files.append(file_path.stem)

    if not problem_files:
        logger.warning(f"No {prefix_char}-code files found in {problems_dir}")
        return

    # Sort by numeric part
    def sort_key(code):
        match = re.match(rf'{prefix_char}(\d+)', code)
        return int(match.group(1)) if match else 0

    problem_files.sort(key=sort_key)

    content = f""".. This file is automatically generated by the ironplc_problemcode Sphinx extension
.. Do not edit manually - your changes will be overwritten

{'=' * len(title)}
{title}
{'=' * len(title)}

.. toctree::
   :maxdepth: 1

"""
    for code in problem_files:
        content += f"   {code} <{code}>\n"

    content += "\n\n"

    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(content)

    logger.info(f"Generated {title} index with {len(problem_files)} codes")


def generate_problem_index(app, config):
    """
    Generate problem code index.rst files for compiler and runtime problems.
    """
    from sphinx.util import logging
    logger = logging.getLogger(__name__)
    srcdir = Path(app.srcdir)

    _generate_index_for(logger, srcdir, Path('reference') / 'compiler' / 'problems', 'P', 'Problem Codes')
    _generate_index_for(logger, srcdir, Path('reference') / 'runtime' / 'problems', 'V', 'Error Codes')

REDIRECT_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Redirecting\u2026</title>
  <link rel="canonical" href="/{new_path}">
  <meta http-equiv="refresh" content="0; url=/{new_path}">
  <script>window.location.replace('/{new_path}' + window.location.search);</script>
</head>
<body>
  <p>This page has moved to <a href="/{new_path}">/{new_path}</a>.</p>
</body>
</html>
"""

# Old path prefix -> new path prefix (relative to build output root)
PROBLEM_REDIRECTS = [
    ('compiler/problems', 'reference/compiler/problems'),
    ('vscode/problems',   'reference/editor/problems'),
    ('runtime/problems',  'reference/runtime/problems'),
]

def generate_redirects(app, exception):
    """Generate redirect HTML pages at old URLs after a successful build."""
    if exception:
        return

    from sphinx.util import logging
    logger = logging.getLogger(__name__)

    outdir = Path(app.outdir)

    for old_prefix, new_prefix in PROBLEM_REDIRECTS:
        new_dir = outdir / new_prefix
        if not new_dir.exists():
            logger.warning(f"Expected output directory not found: {new_dir}")
            continue

        old_dir = outdir / old_prefix
        old_dir.mkdir(parents=True, exist_ok=True)

        for html_file in new_dir.glob('*.html'):
            new_path = f"{new_prefix}/{html_file.name}"
            redirect_file = old_dir / html_file.name
            redirect_file.write_text(
                REDIRECT_TEMPLATE.format(new_path=new_path),
                encoding='utf-8',
            )

        logger.info(f"Generated redirects: {old_prefix}/ -> {new_prefix}/")

def setup(app):
    app.add_directive("problem-summary", ProblemSummary)

    # Connect to the config-inited event to generate the index before building
    app.connect('config-inited', generate_problem_index)
    app.connect('build-finished', generate_redirects)

    return {
        'version': '0.2',
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }