set windows-shell := ["powershell.exe", "-c"]

default: compile

# Runs the continuous integration steps
ci: setup compile

setup:
  pip3 install furo sphinx-inline-tabs sphinx-copybutton pytz

compile:
  sphinx-build -a -W -n -b html . _build
  echo "www.ironplc.com" > _build/CNAME

# Sets the version number for this component.
version version:
  echo "{{version}}" > VERSION

# Removes built files
clean:
  rm -r _build
