set windows-shell := ["powershell.exe", "-c"]

default: compile

# Runs the continuous integration steps
ci: setup compile

setup:
  pip3 install furo sphinx-inline-tabs sphinx-copybutton pytz sphinx-design sphinx-sitemap sphinxext-opengraph

compile:
  sphinx-build -a -W -n -b html . _build
  echo "www.ironplc.com" > _build/CNAME
  # Publish the install script at https://www.ironplc.com/install.sh.
  # This only goes live after partial_install_script_test passes, gating
  # publish-website on a broken installer.
  cp ../compiler/install.sh _build/install.sh

# Sets the version number for this component.
version version:
  echo "{{version}}" > VERSION

# Removes built files
clean:
  rm -rf _build
