name: IronPLC Integration
on:
  pull_request:
    branches:    
      - main
  push:
    branches:
      - main
  # Allow triggering directly
  workflow_dispatch:

jobs:
  ironplcc-tests:
    name: Build IronPLC Compiler
    uses: ./.github/workflows/partial_compiler.yaml
    with:
      commit-ref: ""
      gh-release-tag: ""
      version: "0.0.0"

  vscode-extension:
    name: Build Visual Studio Code Extension
    uses: ./.github/workflows/partial_vscode_extension.yaml
    with:
      commit-ref: ""
      gh-release-tag: ""
      artifact-name: vscode-extension

  docs:
    name: Build Website
    # The website doesn't depend on these but we don't publish
    # if those are failing so we depend on those.
    uses: ./.github/workflows/partial_website.yaml
    with:
      commit-ref: ""
      publish: false
