name: Publish Pre-release
on:
  # Allow triggering directly
  workflow_dispatch:
    inputs:
      gh-release-id:
        required: false
        type: string
        default: ""
        description: 'The Github Release ID to set as pre-release'
      dryrun:
        required: true
        type: boolean
        default: true
        description: 'If set, run as a dry run and do not create the release artifacts'


  # Allow using this workflow from another workflow
  workflow_call:
    inputs:
      gh-release-id:
        required: false
        type: string
        description: 'The Github Release tag to publish to'
      dryrun:
        type: boolean
        description: 'If set, run as a dry run and do not create the release artifacts'
        default: true

jobs:
  publish-prerelease:
    name: Label GitHub Release as Prerelease
    runs-on: ubuntu-latest
    steps:
      # Update the release
      #- name: Label GitHub Release as pre-release
      #  if: ${{ !inputs.dryrun }}
      #  uses: irongut/EditRelease@v1.2.0
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    id: ${{ inputs.gh-release-id }}
      #    prerelease: true
      #    draft: false

      - name: No-op
        run: echo ${{ inputs.gh-release-id }}
        
