name: VS Code Extension
on:
  workflow_call:
    inputs:
      commit-ref:
        required: false
        type: string
        description: 'If not empty, then run for the specified branch name or tag'
      gh-release-tag:
        required: false
        type: string
        description: 'The Github Release tag to publish to'
      artifact-name:
        required: false
        type: string
        description: 'The name of the VSIX artifact to create'
      install-deps:
        required: false
        type: boolean
        default: false

jobs:
  vscode-extension:
    name: Visual Studio Code Extension Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integrations/vscode
    steps:
      # Checkout the repository/fetch input artifacts
      - name: Checkout tag ${{ inputs.commit-ref }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        if: ${{ inputs.commit-ref }}
        with:
          ref: ${{ inputs.commit-ref }}
      - name: Checkout HEAD
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        if: ${{ !inputs.commit-ref }}

      # Configure the execution environment
      - uses: taiki-e/install-action@01159adff8f38113be7211e869405f6f6abf02d7 # just
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: npm
          cache-dependency-path: './integrations/vscode/package-lock.json'
          node-version-file: './integrations/vscode/package.json'
      # Applies when using act to run locally
      - name: Install X server components and Xvfb
        run: sudo apt update && sudo apt install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libdrm2 libgtk-3-0 libgbm1 libasound2 xvfb
        if: ${{ inputs.install-deps }}

      # Execute build recipe
      - name: Install dependencies
        run: just setup
      - name: Build and Test
        run: just ci
      - name: Create VSIX package
        run: just package ironplc-vscode-extension.vsix

      # Save output artifacts
      - name: Upload VSIX to build artifact
        if: ${{ inputs.artifact-name }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ inputs.artifact-name }}
          path: integrations/vscode/ironplc-vscode-extension.vsix
          if-no-files-found: error
      - name: Upload VSIX to GibHub Release
        if: ${{ inputs.gh-release-tag }}
        uses: svenstaro/upload-release-action@b98a3b12e86552593f3e4e577ca8a62aa2f3f22b # v2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ inputs.gh-release-tag }}
          asset_name: ironplc-vscode-extension.vsix
          file: integrations/vscode/ironplc-vscode-extension.vsix
