name: Playground E2E Tests

on:
  # Allow triggering directly
  workflow_dispatch: {}

  # Allow using this workflow from another workflow
  workflow_call: {}

jobs:
  e2e:
    name: Playground E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playground
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Download playground artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: ironplc-playground
          path: ./playground/_build

      # Configure the execution environment
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      # Execute E2E tests
      - name: Run E2E tests
        run: npx playwright test

      # Save artifacts on failure
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: playwright-report
          path: playground/test-results/
          retention-days: 5
